defaultSemverRangePrefix: ""

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@3.x":
    dependencies:
      typescript: ^4.x
  eslint-config-airbnb-typescript@12.x:
    peerDependencies:
      eslint: ^7.x
      eslint-plugin-import: ^2.x
      eslint-plugin-jsx-a11y: ^6.x
      eslint-plugin-react: ^7.x
      eslint-plugin-react-hooks: ^x
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  gatsby-plugin-postcss@3.x:
    peerDependencies:
      webpack: ^4.x
  gatsby-plugin-typescript@2.x:
    peerDependencies:
      gatsby: ^2.x

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

pnpFallbackMode: all

yarnPath: .yarn/releases/yarn-2.4.1.cjs
